version: '3'
services:

  redis-primary:
    image: redis:7.2.2
    command: redis-server --appendonly yes --maxmemory 8mb --maxmemory-policy allkeys-lru
    volumes:
      - ~/data/redis:/data
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  redis-replica:
    image: redis:7.2.2
    command: redis-server --replicaof redis-primary 6379
    volumes:
      - ~/data/redis:/data
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    depends_on:
      - redis-primary

  url-handler:
    image: sjwsteven/url-handler:latest
    ports:
      - "8080:5000"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - redis-primary
      - redis-replica
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 10s
