version: '3'
services:

#  nginx:
#    build: nginx/
#    ports:
#      - "8081:80"
#    depends_on:
#      - url-handler

  redis-primary:
    image: "redis:7.2.2"
    command: redis-server --appendonly yes --maxmemory 8mb --maxmemory-policy allkeys-lru
    volumes:
      - /home/student/election2022/data:/redis_data
    deploy:
      restart_policy:
        condition: always
      placement:
        constraints: [node.role == primary]

  redis-replica:
    image: "redis:7.2.2"
    command: redis-server --replicaof redis-primary 6379
    volumes:
      - /home/student/election2022/data:/redis_data
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == replica]

  url-handler:
    build: url-handler/
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:5000"
    depends_on:
      - redis-primary