version: '3'
services:

  nginx:
      image: sjwsteven/nginx_for_urlhandler:latest
      container_name: nginx
      ports:
        - "8080:8080"
      volumes:
        - ./nginx/nginx.conf:ro
      restart: always
      deploy:
        placement:
          constraints: [node.role == manager]

  redis-primary:
    image: redis:7.2.2
    container_name: redis-primary
    command: redis-server --appendonly yes --maxmemory 8mb --maxmemory-policy allkeys-lru
    volumes:
      - /home/student/election2022/data:/redis_data
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]

  redis-replica:
    image: redis:7.2.2
    container_name: redis-replica
    command: redis-server --replicaof redis-primary 6379
    volumes:
      - /home/student/election2022/data:/redis_data
    restart: always
    deploy:
      placement:
        constraints: [node.role == worker]

  url-handler:
    image: sjwsteven/url-handler:latest
    container_name: url-handler
    restart: always
    deploy:
      placement:
        constraints: [node.role == worker]
    ports:
      - "8080:5000"
    depends_on:
      - redis-primary