version: '3'
services:

  redis-primary:
    image: redis:7.2.2
    container_name: redis-primary
    command: redis-server --appendonly yes --maxmemory 8mb --maxmemory-policy allkeys-lru
    volumes:
      - ~/data/redis:/data
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]

  redis-replica:
    image: redis:7.2.2
    container_name: redis-replica
    command: redis-server --replicaof redis-primary 6379
    volumes:
      - ~/data/redis:/data
    restart: always
    deploy:
      placement:
        constraints: [node.role == worker]

  url-handler:
    image: sjwsteven/url-handler:no-cassandra
    container_name: url-handler
    ports:
      - "8080:5000"
    restart: always
    depends_on:
      - redis-primary