version: '3'
services:

  nginx:
      image: nginx:latest
      container_name: my_nginx_container
      ports:
        - "8080:8080"
      volumes:
        - ./nginx/nginx.conf:ro
      restart: always
      deploy:
        placement:
          constraints: [node.role == manager]

  redis-primary:
    image: "redis:7.2.2"
    command: redis-server --appendonly yes --maxmemory 8mb --maxmemory-policy allkeys-lru
    volumes:
      - /home/student/election2022/data:/redis_data
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]

  redis-replica:
    image: "redis:7.2.2"
    command: redis-server --replicaof redis-primary 6379
    volumes:
      - /home/student/election2022/data:/redis_data
    restart: always
    deploy:
      placement:
        constraints: [node.role == worker]

  url-handler:
    build: url-handler/
    restart: always
    deploy:
      placement:
        constraints: [node.role == worker]
    ports:
      - "8080:5000"
    depends_on:
      - redis-primary